machine:
    ghc:
        version: 8.6.5
    timezone:
        Australia/Brisbane

dependencies:
    override:
        - cabal new-update
        - cabal new-configure
        - cabal new-build --only-dependencies

test:
    override:
        - cabal new-build
    post:
        - git submodule init
        - git submodule update
        - cd _site/ && git checkout master
        - cabal new-run build  

deployment:
    production:
        branch: source
        commands:
            - git config --global user.email circleci@circleci
            - git config --global user.name CircleCI
            - cd _site/ && git status
            - cd _site/ && git add --all
            - cd _site/ && git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
            - cd _site/ && git push origin master
            - git status
            - git add _site/
            - git commit -m "Update _site (`date '+%F %T %Z'`) [ci skip]"
            - git push origin source

